name: Export Postgres Docker Image

on:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Postgres image
        run: docker pull postgres:latest

      - name: Save Postgres image
        run: docker save postgres:latest -o postgres_latest.tar

      - name: Compress image
        run: gzip -9 postgres_latest.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: postgres-docker-image
          path: postgres_latest.tar.gz
