name: Export ntfy Docker Image

on:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Pull ntfy image
        run: docker pull binwiederhier/ntfy:latest

      - name: Save ntfy image
        run: docker save binwiederhier/ntfy:latest -o ntfy_latest.tar

      - name: Compress image
        run: gzip -9 ntfy_latest.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ntfy-docker-image
          path: ntfy_latest.tar.gz
